### ISSUE TITLE
Rationale for introducing token-aware CashAddress type bits

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/cashtokens#32] opened 2022-07-15 07:23 UTC
Suggested rationale

### Wallet Address Type

Because we require transactions involving categorized outputs to be signed using modified signing serialization, funds unintentionally sent to non-upgraded wallets can't be accidentally lost and will be recoverable by importing the recipient's wallet into upgraded software.

The existing [CashAddress](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md#payload) standard supports extending the address through the use of a type bit, which could be used to indicate wallet support for receiving tokens:

>Encoding the size of the hash in the version field ensure that it is possible to check that the length of the address is correct.
>
>| Type bits |      Meaning      | Version byte value |
>| --------: | :---------------: | -----------------: |
>|         0 |       P2KH        |                  0 |
>|         1 |       P2SH        |                  8 |
>
>Further types will be added as new features are added.

However we expect that, over time, most wallets will support receiving and sending tokens.
**Introducing two more address types just to signal readiness to receive tokens would only have a temporary benefit, while the cost of having to maintain two more address encodings would be permanent.**

Therefore, we do NOT recommend a new address type.

### Risks - Wrong Wallet Implementation

If a wallet would obtain a categorized output but be unable to spend it, then it could cause it to temporarily become unusable until the issue is resolved.

This could happen in two ways:

1. Non-upgraded and badly implemented wallet registering a categorized output as one of its own, which is unlikely and [has been discussed](#script-prefix-on-outputs);
2. Upgraded wallet having a bug in transaction building, which can be expected since bugs happen, and not all wallets pass through the same quality assurance processes.

Burning funds by non-upgraded wallets will not be possible since they wouldn't be able to produce a valid signature, and it would at worst result in temporary loss of service - users unable to send their funds until the issue is resolved.
The same would hold for upgraded wallets that are upgraded but have a bug that would prevent them from producing valid transactions.

The riskiest class of bugs is that of an upgraded wallet able to produce signatures but failing to properly account amounts to create categorized "change" outputs that would capture amounts not intended to be spent.
This risk was already present with pure BCH wallet implementations, where the result would be a donation to miners in form of fees.
With this proposal, the risk applies the same to token amounts - but instead of being donated they'd be burned.

This is a risk external to protocol development, and the only mitigation available is to write good documentation and suggest using wallet software that has good quality-assurance processes.
Since most popular wallets have proper processes in place and upgrades are reviewed and tested by multiple developers, we consider this risk to be low.

**Comment by bitjson** [comment] 2022-07-18 18:51
The rationale doesn't address losses incurred by users sending tokens to existing addresses that are not monitored for tokens; this was a huge issue for users at the BCH-BTC split, where users attempted to send BCH to "BTC addresses".

If the receiving wallet/service wasn't capable of monitoring/crediting the user/re-sending the BCH, the BCH was locked for an indefinite period. Some services shut down before giving those users any received BCH, and some clarified their terms to designate any received BCH as forfeited. Likewise, some wallet software was never updated to support sending the received BCH, forcing users to manually export keys, hire recovery services, or abandon their funds.

The CashTokens upgrade is designed to ensure wallets and services are not required to upgrade to remain on the BCH network. If users of token supporting wallets attempt to send tokens to non-upgraded software/services, the tokens will be frozen until/unless the receiver is upgraded. In some cases, existing key handling strategies will prevent new signing strategies (like token signing serialization) from being used with existing private keys; to accept tokens, these systems will need to use new private keys, and any tokens sent to older private keys might be permanently inaccessible. 

**The primary purpose of designating CashToken-specific CashAddress types is to prevent users from unknowingly sending tokens to addresses where the tokens will be inaccessible to the intended recipient.**

> Introducing two more address types just to signal readiness to receive tokens would only have a temporary benefit, while the cost of having to maintain two more address encodings would be permanent.

By design, it will forever be possible to create new token-unaware wallets, e.g. if the wallet creator doesn't expect tokens to ever be useful for the wallet's use case (token support can add non-trivial maintenance cost). **It will always be important for these wallet to continue indicating their non-support for tokens** – i.e. type 0 or 1 addresses.

All CashAddress-compatible software has already paid the cost of maintaining up to 16 types (with a bit reserved for future extensibility), and test vectors have included the proposed types since the format came into use (2018). The real cost here is simply that we are spending 2 more of these available types. The cost is not trivial, but this rationale seems to overstate it.

The CashTokens CHIP would be the first upgrade to reserve new type bits in the CashAddress format since its inception. I'm actually struggling to imagine a more appropriate case to reserve new CashAddress type bits – **if not for tokens, when?**

>  categorized output

Nit: do you mean "outputs with tokens"? I think describing an output as "categorized" is terminology from [`OP_CHECKCOLORVERIFY`](https://github.com/bitjson/cashtokens#op_checkcolorverify)? It seems confusing/incorrect to apply it here – tokens are independent entities that can be placed in outputs, but they don't "color"/"categorize" the satoshis in the output.

**Comment by bitjson** [comment] 2022-07-18 20:20
> How could a private key be prevented from making a certain kind of signature?

If the private key was loaded into some sort of trusted, "Hardware Security Module", the hardware may know how to sign existing transaction types, but the signing code might not be updatable without wiping existing private keys. (Or destroying the module to perform an expensive/risky key extraction in a lab.)

For the record, I strongly prefer multisig over these trusted hardware-centric approaches. Multisig often offers better security diversification and less risk of key loss.

**Comment by imaginaryusername** [comment] 2022-07-18 20:58
Note: 

1. Some wallets are expected to _practically never_ support tokens, and that is okay. The notion that they "will" does not stand, and incurs confusion that will immediately harm BCH for an uncertain "long term" benefit. Please DO introduce the new type bits (but continue to use cashaddr - nobody likes writing new libraries).

2. While we're introducing new bits, note that this is also a golden opportunity to replace the unwieldy `bitcoincash:` prefix with `bch:` . Such use will signal (in my opinion, rightfully) a very visible beginning of a "new era" in BCH brought upon by the accumulation of scripting work since covenants were first enabled as a side benefit of CHECKDATASIG.

**Comment by A60AB5450353F40E** [comment] 2022-07-18 21:09
>if you see bch: , you're on P2SH32, no need to check length

You may still want to have 20b P2SH addresses, they too would benefit from `bch:` but I guess it would conveniently signal that the wallet has been upgraded to an updated standard (even if it chooses to never generate p2sh32 or token addresses), it's like we get a "free" version bump with `bch:`

**Comment by A60AB5450353F40E** [comment] 2022-07-19 06:06
>I had some preliminary feedback from Calin where as maintainer of Electron Cash he'd prefer not to introduce a new format... but now that we have a stronger rationale, let's ask again. :)

asked and answered, copying from Slack:

>Hmm right. You did capture my fear/frustration with a new address type: namely if in some distant or near future ALL wallets support CashTokens, we wouldn't need the type bit and supporting yet another address format is just burden.

>However it's also possible that for the foreseeable future there will be a “split” in support. Some wallets or hw wallets just will never support CashTokens — CashTokens is opt in.

>In that case having two groups of addresses — CT and non CT is a good idea.

>Yeah idk it's all guesswork right?

>I do def buy Jason's argument tho — we did see btc being sent to bch and vice Versa and this happened a bit less when we introduced cashaddr

>Yeah makes sense.

**Comment by bitjson** [comment] 2022-07-26 19:17
Another note for rationale: types `2` and `3` happen to be particularly appropriate because they set bit `2` for the existing formats:

- `p2pkh`: type bits: `0b0000` (`0`)
- `p2sh`: type bits: `0b0001` (`1`)
- `p2pkh+tokens`: type bits: `0b0010` (`2`)
- `p2sh+tokens`: type bits: `0b0011` (`3`)

Future upgrades will have the option of either continuing this scheme (by creating 2 new versions, one with token support and one without) or simply assuming all future address formats require token support.

So e.g. if we add a `p2pk` address (maybe with a MAST/Taproot upgrade), it could be at `0b0100` for "no tokens" and `0b0110` for "with tokens", but choosing `2`/`3` now also doesn't completely lock us into considering that bit to be the "token bit".

Alternatively, we could use bit 4, so the types would be `8`/`9` respectively. If we expect all future address types will have both token/no-token modes, we'd end up with a cleaner scheme by not splitting the space with a token bit. I think there's a reasonable chance we'll also end up with a similar bit to represent "supports fraction satoshis", and in that case we'd almost certainly want these boolean flags to start on the other side of the range... 

Actually, after the earlier discussion around always retaining support for "no token" addresses, I'm now leaning toward using the highest type bit:

- `p2pkh`: type bits: `0b0000` (`0`)
- `p2sh`: type bits: `0b0001` (`1`)
- `p2pkh+tokens`: type bits: `0b1000` (`8`)
- `p2sh+tokens`: type bits: `0b1001` (`9`)

Anyone have other arguments for/against?

**Comment by A60AB5450353F40E** [comment] 2022-07-26 20:19
>Anyone have other arguments for/against?

If we go for the bit, I'm fine with either. Btw, if we need more bits I think we could hack it: use the last bit as extension bit, one that would tell the wallet to interpret X bits of payload as extended data e.g. you'd be encoding "extended" 20b P2SH using the 192-bit encoding, but only 160bits would be the hash, while 32 would be the extended data.

>(maybe with a MAST/Taproot upgrade)

side-note: we kinda got that already with introspection hehe, we can [emulate OP_EVAL](https://medium.com/@bitcoincashautist/emulating-op-eval-using-bitcoin-cash-native-introspection-opcodes-op-utxobytecode-957e4c49169f) using dust utxo "sidecar" inputs which bring in the code to be executed, so I think we can do MAST, and I'm not sure for Taproot (meaning hiding even the existence of an alternate spending path?)

**Comment by cculianu** [comment] 2022-07-31 18:55
Oh I missed this discussion. Negative. Please just populate the type type `enum` from the bottom-up, as you had it before. This is the standard way to populate such values.  E.g. just do:

```
p2pkh: type bits: 0b0000 (0)
p2sh: type bits: 0b0001 (1)
p2pkh+tokens: type bits: 0b0010 (2)
p2sh+tokens: type bits: 0b0011 (3)
```

We lack a crystal ball and we lack the ability to predict the future.  Allocating in the middle of a block of numbers like this is silly and annoying.  Stop trying to be too clever.  There is value in knowing what came first, what came after, etc, historically, from just examining the `enum`'s values as they increase.

Please revert the spec back to what you had before.

**Comment by imaginaryusername** [comment] 2022-07-31 18:58
Agreed, there's no particular reason to leave the middle empty except for some _possible_ aesthetics gain _in the future_ , at the immediate detriment of _current_ implementations. Please revert to 2/3.

**Comment by bitjson** [comment] 2022-08-01 21:55
Ah, good points, thanks!

Agreed, both options allow us to identify a single token bit, and the aesthetic benefit of `8`/`9` is only realized if the "token bit" continues to be optional for future types. If not, we've lost the aesthetic benefit of contiguous and chronological ordering with `2`/`3`. 

So the future value is ambiguous, but there's a non-zero current cost in creating a gap: it prevents the types from being specified as a simple array, and it's slightly more surprising for implementers (requires explanation).

Alright, I'll revert that and fix the test vectors now. Thanks everyone for the comments!

**Comment by cculianu** [comment] 2022-08-01 22:59
1. Nobody is going to do bit-ops on these types like this.
2. If you like to imagine that scenario, you can imagine bit 2 is that bit, and we can stick with 3 & 4 as was originally specified.

**Closed** 2022-09-29 18:03 UTC
