### ISSUE TITLE
TOKEN_PREFIX byte needs to be a unique, unused and invalid op-code; disallow creation of locking scripts with prefix that failed to parse

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#47] opened 2022-07-25 02:51 UTC
This suggestion directly contradicts issue #41 and PR #43.  

If this suggestion were implemented it would simplify and/or reduce the "urgency" and/or criticality of #44, #45 and #46.

Suggestion Summary
---

I think it’s not a great idea for prefix byte to do double duty with the introspection opcode `OP_UTXOTOKENAMOUNT`.  We need to make the `TOKEN_PREFIX` be a unique codepoint that is otherwise an invalid opcode.  See discussion starting with my comment here:  https://github.com/bitjson/cashtokens/issues/41#issuecomment-1193218237

Suggest: `0xbf` as the token prefix .

Additionally: Post-activation, we should **disallow** the creation of locking scripts that start with `0xbf` but fail to parse as token data -- to save potential headaches in the future should we somehow loosen the serialization rules or otherwise modify them for the token data.

Rationale
---

While implementing #41, I noticed a couple of corner cases arise if we have the PREFIX_BYTE do double-duty as an op-code.  

- It means that we need to be **very careful** about what is a **consensus failure** and what is a **serialization failure**.    
  - This is because if we fail to parse a byte stream as token data (i.e. a **serialization failure**), the byte stream just ends up entirely put into the beginning of a `scriptPubKey` (locking script) of an output.  And entirely different consensus rules now apply to that data, as opposed to an output containing token data.  Thus, it puts a lot of burden on this specification to clearly delineate what is a **parse error** versus what is disallowed for **consensus**.  See issue #44 
- What's more, some locking scripts may unintentionally get "parsed" as token data when they intended to just have `0xd0` be their first op-code (very rare corner case, requires miners to mine these, but the fact that this is possible is troubling).... This "quirk" thus makes some subset of the set of all possible theoretical locking scripts beginning with `0xd0` impossible to construct.

If we use a **unique codepoint** that does **no double-duty** as an op-code (and is a disabled code-point otherwise),.. the above caveats *completely evaporate*.

---

Update: This has been implemented already here: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/merge_requests/1580/diffs?commit_id=874f825c8f33b19327cf6c55b62782b62548215f

**Comment by imaginaryusername** [comment] 2022-07-25 04:51
ACK

**Comment by A60AB5450353F40E** [comment] 2022-07-25 06:27
ACK

**Comment by cculianu** [comment] 2022-07-25 16:17
Implemented in my MR here: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/merge_requests/1580/diffs?commit_id=874f825c8f33b19327cf6c55b62782b62548215f


Note I'm also disallowing creation of unparseable garbage outputs that begin with PREFIX_BYTE (post-activation).

**Comment by bitjson** [comment] 2022-07-25 20:10
💯 Agreed – @cculianu do you strongly prefer `0xbf` over reverting to `0xef`? 

`0xbf` could split up any future nullary introspection operations, while `0xef` is as far out of the way of true opcodes as possible while leaving the `0xf` range open for a multi-byte expansion (if single-byte codepoints are ever exhausted). And if future upgrades used this prefix strategy (e.g. fractional satoshis/fungible tokens), those prefixes could be located together by counting down from `0xef` (`0xee`, `0xed`, etc.).

**Comment by zander** [comment] 2022-07-25 20:18
As an point of order here, I did instantly check the initially suggested opcode to be a duplicate or not, but unfortunatley last years upgrade is still unfinished and the official specification doesn't list those codepoints.

https://documentation.cash/protocol/blockchain/script

It would be really nice if those that pushed those upgrades last year can finish their work and update the spec so not only people like cculianu who is in the core team can notice them.  
I really do think that is not something to be ignored, as issues like this would be much easier to catch.

**Comment by cculianu** [comment] 2022-07-25 21:11
> 0xbf could split up any future nullary introspection operations, while 0xef is as far out of the way of true opcodes as possible while leaving the 0xf range open for a multi-byte expansion (if single-byte codepoints are ever exhausted). And if future upgrades used this prefix strategy (e.g. fractional satoshis/fungible tokens), those prefixes could be located together by counting down from 0xef (0xee, 0xed, etc.).

See [my other comment here](https://github.com/bitjson/cashtokens/issues/41#issuecomment-1194632062) about why `0xef` is super awkward for BCHN.  Please let's just save me some sanity and some hours and just go with `0xbf`.

**Comment by cculianu** [comment] 2022-07-25 21:15
> It would be really nice if those that pushed those upgrades last year can finish their work and update the spec so not only people like cculianu who is in the core team can notice them.
I really do think that is not something to be ignored, as issues like this would be much easier to catch.

@zander  - I have no idea who maintains the spec and I'm sorry it's not updated.  Somebody definitely should update it on all websites that publish the opcode specs.. for sure.

**Comment by zander** [comment] 2022-07-26 09:28
> 0xbf could split up any future [] operations

backup up calin here, this is a clean idea but doesn't seem relevant in real life usage later anyway. We name them to avoid such inevitable inconsistencies to be an issue.

>  I have no idea who maintains the spec 

I think the problem is, nobody maintains it.

Last night BCA was the hero that made a PR against the verde repo and I merged it for the flowee repo so now we have this updated! https://flowee.org/docs/spec/blockchain/script/#introspection

**Closed** 2022-09-29 18:03 UTC
